---
driver:
  name: vagrant
  require_chef_omnibus: 11.10.4

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: ~/.chef/encrypted_data_bag_secret
  data_bags_path: ../../data_bags
  environments_path: ../../environments
  client_rb:
    environment: '_default'

platforms:
- name: ubuntu-12.04
  driver_config:
    customize:
      cpus: 4
      memory: 1536

suites:
  - name: default
    run_list:
      - recipe[et_loading_dock_app::default]
