---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret
  data_bags_path: <%= ENV['CHEF_REPO'] %>/data_bags
  environments_path: <%= ENV['CHEF_REPO'] %>/environments
  client_rb:
    environment: '_default'

platforms:
- name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[et_loading_dock_app::default]
